// Türkçe Kelime Veritabanı - 1000+ kelime
export const wordDatabase = [
  // 2-3 harf (100+ kelime)
  'ev', 'su', 'el', 'göz', 'kol', 'baş', 'ayak', 'dil', 'yüz', 'saç', 'diş', 'kulak', 'burun', 'ağız', 'boyun',
  'bir', 'iki', 'üç', 'dört', 'beş', 'altı', 'yedi', 'sekiz', 'dokuz', 'on', 'yüz', 'bin', 'milyon',
  'at', 'it', 'ot', 'ok', 'ip', 'iş', 'aş', 'üst', 'alt', 'orta', 'son', 'ilk', 'ara', 'yan', 'ön', 'arka',
  'ay', 'gün', 'yıl', 'saat', 'gece', 'sabah', 'öğle', 'akşam', 'an', 'zaman', 'yer', 'yol', 'yön',
  'aç', 'tok', 'iyi', 'kötü', 'güzel', 'çirkin', 'yeni', 'eski', 'büyük', 'küçük', 'uzun', 'kısa',
  'sıcak', 'soğuk', 'sert', 'yumuşak', 'ağır', 'hafif', 'hızlı', 'yavaş', 'kolay', 'zor',
  'var', 'yok', 'çok', 'az', 'tam', 'yarım', 'boş', 'dolu', 'açık', 'kapalı', 'dar', 'geniş',
  'ben', 'sen', 'o', 'biz', 'siz', 'onlar', 'kim', 'ne', 'nerede', 'nasıl', 'niçin', 'neden',
  
  // 4 harf (200+ kelime)
  'anne', 'baba', 'dede', 'nine', 'amca', 'dayı', 'hala', 'teyze', 'kardeş', 'çocuk', 'bebek',
  'kedi', 'köpek', 'kuş', 'balık', 'fare', 'inek', 'koyun', 'keçi', 'tavuk', 'horoz', 'ördek', 'kaz',
  'aslan', 'kaplan', 'ayı', 'kurt', 'tilki', 'tavşan', 'sincap', 'kirpi', 'kunduz', 'samur',
  'elma', 'armut', 'muz', 'üzüm', 'erik', 'kiraz', 'ayva', 'incir', 'nar', 'hurma', 'kivi',
  'masa', 'koltuk', 'yatak', 'dolap', 'kapı', 'pencere', 'duvar', 'tavan', 'zemin', 'halı', 'perde',
  'okul', 'sınıf', 'ders', 'sınav', 'ödev', 'tatil', 'kitap', 'kalem', 'defter', 'silgi', 'çanta',
  'araba', 'otobüs', 'tren', 'uçak', 'gemi', 'tekne', 'bisiklet', 'motor', 'taksi', 'metro',
  'güneş', 'ay', 'yıldız', 'bulut', 'yağmur', 'kar', 'dolu', 'sis', 'rüzgar', 'fırtına', 'kasırga',
  'deniz', 'göl', 'nehir', 'ırmak', 'dere', 'çay', 'pınar', 'kaynak', 'şelale', 'gölet',
  'dağ', 'tepe', 'vadi', 'ova', 'yayla', 'plato', 'bozkır', 'çöl', 'orman', 'koru', 'bağ', 'bahçe',
  'ekmek', 'süt', 'yumurta', 'peynir', 'zeytin', 'bal', 'reçel', 'tereyağ', 'yoğurt', 'ayran',
  'çorba', 'pilav', 'börek', 'köfte', 'kebap', 'dolma', 'sarma', 'meze', 'salata', 'tatlı',
  'kırmızı', 'mavi', 'yeşil', 'sarı', 'siyah', 'beyaz', 'turuncu', 'mor', 'pembe', 'gri', 'kahverengi',
  'bahar', 'yaz', 'sonbahar', 'kış', 'mevsim', 'iklim', 'hava', 'sıcaklık', 'nem', 'basınç',
  'sevgi', 'aşk', 'nefret', 'korku', 'öfke', 'mutluluk', 'üzüntü', 'heyecan', 'umut', 'hayal',
  'barış', 'savaş', 'özgürlük', 'esaret', 'adalet', 'haksızlık', 'doğru', 'yanlış', 'iyi', 'kötü',
  
  // 5 harf (250+ kelime)
  'bilgisayar', 'telefon', 'tablet', 'kamera', 'ekran', 'klavye', 'fare', 'yazıcı', 'tarayıcı',
  'doktor', 'hemşire', 'eczacı', 'dişçi', 'veteriner', 'cerrah', 'terapist', 'psikolog',
  'öğretmen', 'müdür', 'müfettiş', 'öğrenci', 'talebe', 'mezun', 'stajyer', 'asistan',
  'mühendis', 'mimar', 'avukat', 'hakim', 'savcı', 'noter', 'icra', 'mahkeme',
  'polis', 'asker', 'komutan', 'general', 'albay', 'yüzbaşı', 'teğmen', 'onbaşı',
  'pilot', 'kaptan', 'tayfa', 'mürettebat', 'hostes', 'kabin', 'kokpit', 'pist',
  'aşçı', 'garson', 'komi', 'şef', 'patron', 'müdür', 'memur', 'işçi', 'usta', 'çırak',
  'ressam', 'heykeltıraş', 'müzisyen', 'şarkıcı', 'dansçı', 'oyuncu', 'yönetmen', 'senarist',
  'yazar', 'şair', 'romancı', 'öykücü', 'eleştirmen', 'editör', 'çevirmen', 'redaktör',
  'gazeteci', 'muhabir', 'foto muhabir', 'kameraman', 'sunucu', 'spiker', 'yorumcu',
  'sporcu', 'futbolcu', 'basketbolcu', 'voleybolcu', 'tenisçi', 'yüzücü', 'koşucu', 'atlet',
  'domates', 'salatalık', 'biber', 'patlıcan', 'havuç', 'soğan', 'sarımsak', 'patates', 'kabak',
  'portakal', 'mandalina', 'limon', 'greyfurt', 'karpuz', 'kavun', 'çilek', 'şeftali', 'kayısı',
  'televizyon', 'radyo', 'gazete', 'dergi', 'kitap', 'roman', 'hikaye', 'şiir', 'makale',
  'hastane', 'klinik', 'poliklinik', 'acil', 'ameliyathane', 'yoğun bakım', 'eczane', 'laboratuvar',
  'üniversite', 'fakülte', 'bölüm', 'anabilim', 'enstitü', 'rektörlük', 'dekanlık', 'bölüm başkanlığı',
  'kütüphane', 'arşiv', 'müze', 'galeri', 'sergi', 'koleksiyon', 'eser', 'yapıt',
  'restoran', 'lokanta', 'kafe', 'pastane', 'kahvehane', 'çayhane', 'büfe', 'kantin',
  'market', 'süpermarket', 'bakkal', 'manav', 'kasap', 'balıkçı', 'fırın', 'pastane',
  'sinema', 'tiyatro', 'opera', 'bale', 'konser', 'gösteri', 'etkinlik', 'festival',
  'havaalanı', 'istasyon', 'terminal', 'liman', 'iskele', 'rıhtım', 'durak', 'gar',
  'matematik', 'geometri', 'cebir', 'trigonometri', 'analiz', 'istatistik', 'olasılık',
  'fizik', 'kimya', 'biyoloji', 'astronomi', 'jeoloji', 'coğrafya', 'tarih', 'felsefe',
  'edebiyat', 'dil bilim', 'sosyoloji', 'psikoloji', 'antropoloji', 'arkeoloji', 'etnoloji',
  'ekonomi', 'işletme', 'muhasebe', 'finans', 'pazarlama', 'yönetim', 'ticaret', 'sanayi',
  'politika', 'demokrasi', 'cumhuriyet', 'monarşi', 'oligarşi', 'anarşi', 'diktatörlük',
  'anayasa', 'kanun', 'yasa', 'tüzük', 'yönetmelik', 'genelge', 'talimat', 'emir',
  'parlamento', 'meclis', 'senato', 'kongre', 'kurul', 'komisyon', 'komite', 'heyet',
  
  // 6-7 harf (250+ kelime)
  'bilgisayar', 'programlama', 'yazılım', 'donanım', 'internet', 'ağ', 'sunucu', 'istemci',
  'veritabanı', 'algoritma', 'veri yapısı', 'nesne', 'sınıf', 'fonksiyon', 'değişken',
  'mühendislik', 'mimarlık', 'inşaat', 'proje', 'tasarım', 'planlama', 'uygulama', 'denetim',
  'teknoloji', 'inovasyon', 'buluş', 'patent', 'telif', 'lisans', 'sertifika', 'diploma',
  'çikolata', 'dondurma', 'pasta', 'kurabiye', 'kek', 'tart', 'sufle', 'puding',
  'hamburger', 'sandviç', 'tost', 'pizza', 'makarna', 'spagetti', 'lazanya', 'ravioli',
  'kahvaltı', 'öğle yemeği', 'akşam yemeği', 'ara öğün', 'atıştırmalık', 'içecek', 'yemek',
  'futbol', 'basketbol', 'voleybol', 'hentbol', 'tenis', 'badminton', 'masa tenisi', 'golf',
  'yüzme', 'dalış', 'sörf', 'yelken', 'kürek', 'kano', 'rafting', 'su kayağı',
  'koşu', 'maraton', 'sprint', 'atletizm', 'jimnastik', 'cimnastik', 'akrobasi', 'tramplen',
  'güreş', 'boks', 'karate', 'judo', 'taekwondo', 'aikido', 'kung fu', 'kickboks',
  'satranç', 'dama', 'tavla', 'okey', 'briç', 'poker', 'iskambil', 'zar',
  'müzik', 'şarkı', 'türkü', 'marş', 'ilahi', 'beste', 'melodi', 'ritim', 'armoni',
  'enstrüman', 'piyano', 'keman', 'gitar', 'bağlama', 'davul', 'trompet', 'flüt',
  'resim', 'tablo', 'portre', 'manzara', 'natürmort', 'soyut', 'figüratif', 'empresyonizm',
  'heykel', 'büst', 'anıt', 'rölyef', 'kabartma', 'oyma', 'yontu', 'seramik',
  'edebiyat', 'roman', 'hikaye', 'öykü', 'masal', 'fabl', 'destan', 'efsane',
  'şiir', 'manzum', 'nazım', 'nesir', 'kafiye', 'redif', 'vezin', 'aruz',
  'tiyatro', 'oyun', 'perde', 'sahne', 'dekor', 'kostüm', 'makyaj', 'ışık',
  'sinema', 'film', 'senaryo', 'yönetmen', 'oyuncu', 'kamera', 'kurgu', 'montaj',
  
  // 8+ harf (200+ kelime)
  'cumhuriyet', 'demokrasi', 'özgürlük', 'bağımsızlık', 'egemenlik', 'hükümdar', 'vatandaş',
  'mühendislik', 'programlama', 'teknoloji', 'bilgisayar', 'elektronik', 'mekanik', 'elektrik',
  'mimarlık', 'şehircilik', 'peyzaj', 'restorasyon', 'renovasyon', 'tadilat', 'dekorasyon',
  'üniversite', 'akademi', 'enstitü', 'konservatuvar', 'yüksekokul', 'meslek yüksekokulu',
  'kütüphane', 'arşiv', 'dokümantasyon', 'katalog', 'bibliyografya', 'referans', 'kaynak',
  'laboratuvar', 'deney', 'gözlem', 'analiz', 'sentez', 'hipotez', 'teori', 'kanun',
  'hastane', 'poliklinik', 'dispanser', 'sağlık ocağı', 'aile sağlığı', 'acil servis',
  'restoran', 'lokanta', 'kafeterya', 'kantin', 'yemekhane', 'aşevi', 'mutfak',
  'havaalanı', 'terminal', 'pist', 'hangar', 'kule', 'kontrol', 'güvenlik', 'gümrük',
  'televizyon', 'yayın', 'program', 'dizi', 'belgesel', 'haber', 'spor', 'müzik',
  'matematik', 'geometri', 'trigonometri', 'logaritma', 'integral', 'türev', 'limit',
  'astronomi', 'astroloji', 'kozmoloji', 'galaksi', 'yıldız', 'gezegen', 'uydu',
  'coğrafya', 'jeoloji', 'jeomorfoloji', 'hidrografi', 'klimatoloji', 'kartografya',
  'biyoloji', 'botanik', 'zooloji', 'mikrobiyoloji', 'genetik', 'ekoloji', 'anatomi',
  'psikoloji', 'psikiyatri', 'nöroloji', 'sosyoloji', 'antropoloji', 'arkeoloji',
  'ekonomi', 'makroekonomi', 'mikroekonomi', 'ekonometri', 'finans', 'muhasebe',
  'felsefe', 'mantık', 'etik', 'estetik', 'metafizik', 'epistemoloji', 'ontoloji',
  'edebiyat', 'dilbilim', 'semantik', 'sentaks', 'morfoloji', 'fonetik', 'fonoloji'
];
