// Türkçe Kelime Veritabanı - 1000+ kelime
export const wordDatabase = [
  // 2-3 harf (100+ kelime)
  'ev', 'su', 'el', 'göz', 'kol', 'baş', 'ayak', 'dil', 'yüz', 'saç', 'diş', 'kulak', 'burun', 'ağız', 'boyun',
  'bir', 'iki', 'üç', 'dört', 'beş', 'altı', 'yedi', 'sekiz', 'dokuz', 'on', 'yüz', 'bin', 'milyon',
  'at', 'it', 'ot', 'ok', 'ip', 'iş', 'aş', 'üst', 'alt', 'orta', 'son', 'ilk', 'ara', 'yan', 'ön', 'arka',
  'ay', 'gün', 'yıl', 'saat', 'gece', 'sabah', 'öğle', 'akşam', 'an', 'zaman', 'yer', 'yol', 'yön',
  'aç', 'tok', 'iyi', 'kötü', 'güzel', 'çirkin', 'yeni', 'eski', 'büyük', 'küçük', 'uzun', 'kısa',
  'sıcak', 'soğuk', 'sert', 'yumuşak', 'ağır', 'hafif', 'hızlı', 'yavaş', 'kolay', 'zor',
  'var', 'yok', 'çok', 'az', 'tam', 'yarım', 'boş', 'dolu', 'açık', 'kapalı', 'dar', 'geniş',
  'ben', 'sen', 'o', 'biz', 'siz', 'onlar', 'kim', 'ne', 'nerede', 'nasıl', 'niçin', 'neden',
  
  // 4 harf (200+ kelime)
  'anne', 'baba', 'dede', 'nine', 'amca', 'dayı', 'hala', 'teyze', 'kardeş', 'çocuk', 'bebek',
  'kedi', 'köpek', 'kuş', 'balık', 'fare', 'inek', 'koyun', 'keçi', 'tavuk', 'horoz', 'ördek', 'kaz',
  'aslan', 'kaplan', 'ayı', 'kurt', 'tilki', 'tavşan', 'sincap', 'kirpi', 'kunduz', 'samur',
  'elma', 'armut', 'muz', 'üzüm', 'erik', 'kiraz', 'ayva', 'incir', 'nar', 'hurma', 'kivi',
  'masa', 'koltuk', 'yatak', 'dolap', 'kapı', 'pencere', 'duvar', 'tavan', 'zemin', 'halı', 'perde',
  'okul', 'sınıf', 'ders', 'sınav', 'ödev', 'tatil', 'kitap', 'kalem', 'defter', 'silgi', 'çanta',
  'araba', 'otobüs', 'tren', 'uçak', 'gemi', 'tekne', 'bisiklet', 'motor', 'taksi', 'metro',
  'güneş', 'ay', 'yıldız', 'bulut', 'yağmur', 'kar', 'dolu', 'sis', 'rüzgar', 'fırtına', 'kasırga',
  'deniz', 'göl', 'nehir', 'ırmak', 'dere', 'çay', 'pınar', 'kaynak', 'şelale', 'gölet',
  'dağ', 'tepe', 'vadi', 'ova', 'yayla', 'plato', 'bozkır', 'çöl', 'orman', 'koru', 'bağ', 'bahçe',
  'ekmek', 'süt', 'yumurta', 'peynir', 'zeytin', 'bal', 'reçel', 'tereyağ', 'yoğurt', 'ayran',
  'çorba', 'pilav', 'börek', 'köfte', 'kebap', 'dolma', 'sarma', 'meze', 'salata', 'tatlı',
  'kırmızı', 'mavi', 'yeşil', 'sarı', 'siyah', 'beyaz', 'turuncu', 'mor', 'pembe', 'gri', 'kahverengi',
  'bahar', 'yaz', 'sonbahar', 'kış', 'mevsim', 'iklim', 'hava', 'sıcaklık', 'nem', 'basınç',
  'sevgi', 'aşk', 'nefret', 'korku', 'öfke', 'mutluluk', 'üzüntü', 'heyecan', 'umut', 'hayal',
  'barış', 'savaş', 'özgürlük', 'esaret', 'adalet', 'haksızlık', 'doğru', 'yanlış', 'iyi', 'kötü',
  
  // 5 harf (250+ kelime)
  'bilgisayar', 'telefon', 'tablet', 'kamera', 'ekran', 'klavye', 'fare', 'yazıcı', 'tarayıcı',
  'doktor', 'hemşire', 'eczacı', 'dişçi', 'veteriner', 'cerrah', 'terapist', 'psikolog',
  'öğretmen', 'müdür', 'müfettiş', 'öğrenci', 'talebe', 'mezun', 'stajyer', 'asistan',
  'mühendis', 'mimar', 'avukat', 'hakim', 'savcı', 'noter', 'icra', 'mahkeme',
  'polis', 'asker', 'komutan', 'general', 'albay', 'yüzbaşı', 'teğmen', 'onbaşı',
  'pilot', 'kaptan', 'tayfa', 'mürettebat', 'hostes', 'kabin', 'kokpit', 'pist',
  'aşçı', 'garson', 'komi', 'şef', 'patron', 'müdür', 'memur', 'işçi', 'usta', 'çırak',
  'ressam', 'heykeltıraş', 'müzisyen', 'şarkıcı', 'dansçı', 'oyuncu', 'yönetmen', 'senarist',
  'yazar', 'şair', 'romancı', 'öykücü', 'eleştirmen', 'editör', 'çevirmen', 'redaktör',
  'gazeteci', 'muhabir', 'foto muhabir', 'kameraman', 'sunucu', 'spiker', 'yorumcu',
  'sporcu', 'futbolcu', 'basketbolcu', 'voleybolcu', 'tenisçi', 'yüzücü', 'koşucu', 'atlet',
  'domates', 'salatalık', 'biber', 'patlıcan', 'havuç', 'soğan', 'sarımsak', 'patates', 'kabak',
  'portakal', 'mandalina', 'limon', 'greyfurt', 'karpuz', 'kavun', 'çilek', 'şeftali', 'kayısı',
  'televizyon', 'radyo', 'gazete', 'dergi', 'kitap', 'roman', 'hikaye', 'şiir', 'makale',
  'hastane', 'klinik', 'poliklinik', 'acil', 'ameliyathane', 'yoğun bakım', 'eczane', 'laboratuvar',
  'üniversite', 'fakülte', 'bölüm', 'anabilim', 'enstitü', 'rektörlük', 'dekanlık', 'bölüm başkanlığı',
  'kütüphane', 'arşiv', 'müze', 'galeri', 'sergi', 'koleksiyon', 'eser', 'yapıt',
  'restoran', 'lokanta', 'kafe', 'pastane', 'kahvehane', 'çayhane', 'büfe', 'kantin',
  'market', 'süpermarket', 'bakkal', 'manav', 'kasap', 'balıkçı', 'fırın', 'pastane',
  'sinema', 'tiyatro', 'opera', 'bale', 'konser', 'gösteri', 'etkinlik', 'festival',
  'havaalanı', 'istasyon', 'terminal', 'liman', 'iskele', 'rıhtım', 'durak', 'gar',
  'matematik', 'geometri', 'cebir', 'trigonometri', 'analiz', 'istatistik', 'olasılık',
  'fizik', 'kimya', 'biyoloji', 'astronomi', 'jeoloji', 'coğrafya', 'tarih', 'felsefe',
  'edebiyat', 'dil bilim', 'sosyoloji', 'psikoloji', 'antropoloji', 'arkeoloji', 'etnoloji',
  'ekonomi', 'işletme', 'muhasebe', 'finans', 'pazarlama', 'yönetim', 'ticaret', 'sanayi',
  'politika', 'demokrasi', 'cumhuriyet', 'monarşi', 'oligarşi', 'anarşi', 'diktatörlük',
  'anayasa', 'kanun', 'yasa', 'tüzük', 'yönetmelik', 'genelge', 'talimat', 'emir',
  'parlamento', 'meclis', 'senato', 'kongre', 'kurul', 'komisyon', 'komite', 'heyet',
  
  // 6-7 harf (250+ kelime)
  'bilgisayar', 'programlama', 'yazılım', 'donanım', 'internet', 'ağ', 'sunucu', 'istemci',
  'veritabanı', 'algoritma', 'veri yapısı', 'nesne', 'sınıf', 'fonksiyon', 'değişken',
  'mühendislik', 'mimarlık', 'inşaat', 'proje', 'tasarım', 'planlama', 'uygulama', 'denetim',
  'teknoloji', 'inovasyon', 'buluş', 'patent', 'telif', 'lisans', 'sertifika', 'diploma',
  'çikolata', 'dondurma', 'pasta', 'kurabiye', 'kek', 'tart', 'sufle', 'puding',
  'hamburger', 'sandviç', 'tost', 'pizza', 'makarna', 'spagetti', 'lazanya', 'ravioli',
  'kahvaltı', 'öğle yemeği', 'akşam yemeği', 'ara öğün', 'atıştırmalık', 'içecek', 'yemek',
  'futbol', 'basketbol', 'voleybol', 'hentbol', 'tenis', 'badminton', 'masa tenisi', 'golf',
  'yüzme', 'dalış', 'sörf', 'yelken', 'kürek', 'kano', 'rafting', 'su kayağı',
  'koşu', 'maraton', 'sprint', 'atletizm', 'jimnastik', 'cimnastik', 'akrobasi', 'tramplen',
  'güreş', 'boks', 'karate', 'judo', 'taekwondo', 'aikido', 'kung fu', 'kickboks',
  'satranç', 'dama', 'tavla', 'okey', 'briç', 'poker', 'iskambil', 'zar',
  'müzik', 'şarkı', 'türkü', 'marş', 'ilahi', 'beste', 'melodi', 'ritim', 'armoni',
  'enstrüman', 'piyano', 'keman', 'gitar', 'bağlama', 'davul', 'trompet', 'flüt',
  'resim', 'tablo', 'portre', 'manzara', 'natürmort', 'soyut', 'figüratif', 'empresyonizm',
  'heykel', 'büst', 'anıt', 'rölyef', 'kabartma', 'oyma', 'yontu', 'seramik',
  'edebiyat', 'roman', 'hikaye', 'öykü', 'masal', 'fabl', 'destan', 'efsane',
  'şiir', 'manzum', 'nazım', 'nesir', 'kafiye', 'redif', 'vezin', 'aruz',
  'tiyatro', 'oyun', 'perde', 'sahne', 'dekor', 'kostüm', 'makyaj', 'ışık',
  'sinema', 'film', 'senaryo', 'yönetmen', 'oyuncu', 'kamera', 'kurgu', 'montaj',
  
  // 8+ harf (200+ kelime)
  'cumhuriyet', 'demokrasi', 'özgürlük', 'bağımsızlık', 'egemenlik', 'hükümdar', 'vatandaş',
  'mühendislik', 'programlama', 'teknoloji', 'bilgisayar', 'elektronik', 'mekanik', 'elektrik',
  'mimarlık', 'şehircilik', 'peyzaj', 'restorasyon', 'renovasyon', 'tadilat', 'dekorasyon',
  'üniversite', 'akademi', 'enstitü', 'konservatuvar', 'yüksekokul', 'meslek yüksekokulu',
  'kütüphane', 'arşiv', 'dokümantasyon', 'katalog', 'bibliyografya', 'referans', 'kaynak',
  'laboratuvar', 'deney', 'gözlem', 'analiz', 'sentez', 'hipotez', 'teori', 'kanun',
  'hastane', 'poliklinik', 'dispanser', 'sağlık ocağı', 'aile sağlığı', 'acil servis',
  'restoran', 'lokanta', 'kafeterya', 'kantin', 'yemekhane', 'aşevi', 'mutfak',
  'havaalanı', 'terminal', 'pist', 'hangar', 'kule', 'kontrol', 'güvenlik', 'gümrük',
  'televizyon', 'yayın', 'program', 'dizi', 'belgesel', 'haber', 'spor', 'müzik',
  'matematik', 'geometri', 'trigonometri', 'logaritma', 'integral', 'türev', 'limit',
  'astronomi', 'astroloji', 'kozmoloji', 'galaksi', 'yıldız', 'gezegen', 'uydu',
  'coğrafya', 'jeoloji', 'jeomorfoloji', 'hidrografi', 'klimatoloji', 'kartografya',
  'biyoloji', 'botanik', 'zooloji', 'mikrobiyoloji', 'genetik', 'ekoloji', 'anatomi',
  'psikoloji', 'psikiyatri', 'nöroloji', 'sosyoloji', 'antropoloji', 'arkeoloji',
  'ekonomi', 'makroekonomi', 'mikroekonomi', 'ekonometri', 'finans', 'muhasebe',
  'felsefe', 'mantık', 'etik', 'estetik', 'metafizik', 'epistemoloji', 'ontoloji',
  'edebiyat', 'dilbilim', 'semantik', 'sentaks', 'morfoloji', 'fonetik', 'fonoloji',
  
  // Ek 1000 kelime - Günlük hayat ve çeşitli kategoriler
  'çiçek', 'gül', 'lale', 'karanfil', 'papatya', 'menekşe', 'orkide', 'zambak', 'sümbül', 'nergis',
  'ağaç', 'çam', 'meşe', 'çınar', 'kavak', 'söğüt', 'akasya', 'ıhlamur', 'kestane', 'ceviz',
  'meyve', 'sebze', 'tahıl', 'baklagil', 'kuruyemiş', 'baharat', 'çerez', 'içecek', 'yiyecek',
  'kahve', 'çay', 'kola', 'meyve suyu', 'gazoz', 'limonata', 'şalgam', 'boza', 'sahlep',
  'pasta', 'kurabiye', 'kek', 'turta', 'tart', 'sufle', 'puding', 'muhallebi', 'sütlaç',
  'baklava', 'kadayıf', 'künefe', 'lokum', 'helva', 'şekerleme', 'çikolata', 'bonbon',
  'gömlek', 'pantolon', 'etek', 'elbise', 'ceket', 'mont', 'kaban', 'yelek', 'hırka',
  'ayakkabı', 'bot', 'sandalet', 'terlik', 'spor ayakkabı', 'topuklu', 'babet', 'çizme',
  'şapka', 'bere', 'kasket', 'fötr', 'takke', 'bone', 'bandana', 'türban', 'eşarp',
  'çorap', 'çamaşır', 'iç çamaşırı', 'pijama', 'gecelik', 'sabahlık', 'bornoz', 'havlu',
  'yüzük', 'kolye', 'küpe', 'bilezik', 'broş', 'toka', 'kravat', 'kemer', 'saat',
  'çanta', 'valiz', 'bavul', 'sırt çantası', 'el çantası', 'cüzdan', 'para kesesi', 'kılıf',
  'mobilya', 'sandalye', 'tabure', 'kanepe', 'sehpa', 'konsol', 'vitrin', 'komodin', 'şifonyer',
  'lamba', 'avize', 'abajur', 'aplik', 'spot', 'led', 'ampul', 'aydınlatma', 'ışık',
  'buzdolabı', 'fırın', 'ocak', 'mikrodalga', 'çamaşır makinesi', 'bulaşık makinesi', 'süpürge',
  'ütü', 'blender', 'mikser', 'robot', 'tost makinesi', 'kahve makinesi', 'çay makinesi',
  'tabak', 'çanak', 'kase', 'bardak', 'fincan', 'tas', 'sürahi', 'ibrik', 'çaydanlık',
  'kaşık', 'çatal', 'bıçak', 'kepçe', 'maşa', 'spatula', 'kevgir', 'süzgeç', 'rende',
  'tencere', 'tava', 'düdüklü', 'güveç', 'sahan', 'tepsi', 'fırın kabı', 'kek kalıbı',
  'müzik', 'şarkı', 'türkü', 'marş', 'ilahi', 'beste', 'melodi', 'ritim', 'armoni',
  'enstrüman', 'piyano', 'keman', 'gitar', 'bağlama', 'ud', 'kanun', 'ney', 'zurna',
  'davul', 'darbuka', 'def', 'zil', 'trompet', 'saksafon', 'klarnet', 'flüt', 'obua',
  'orkestra', 'koro', 'solist', 'şef', 'virtüöz', 'besteci', 'söz yazarı', 'aranjör',
  'konser', 'resital', 'gösteri', 'performans', 'sahne', 'perde', 'dekor', 'kostüm',
  'tiyatro', 'opera', 'bale', 'dans', 'müzikal', 'drama', 'komedi', 'trajedi', 'fars',
  'sinema', 'film', 'dizi', 'belgesel', 'animasyon', 'kısa film', 'uzun metraj', 'senaryo',
  'yönetmen', 'yapımcı', 'oyuncu', 'figüran', 'dublör', 'makyöz', 'kostümcü', 'ışıkçı',
  'kamera', 'objektif', 'tripod', 'flaş', 'deklanşör', 'diyafram', 'enstantane', 'pozlama',
  'fotoğraf', 'resim', 'tablo', 'portre', 'manzara', 'natürmort', 'soyut', 'figüratif',
  'boya', 'fırça', 'palet', 'tuval', 'şövale', 'kalem', 'pastel', 'suluboya', 'yağlıboya',
  'heykel', 'büst', 'rölyef', 'anıt', 'maket', 'kil', 'mermer', 'bronz', 'alçı',
  'mimari', 'yapı', 'bina', 'gökdelen', 'villa', 'köşk', 'saray', 'kale', 'kule',
  'köprü', 'viyadük', 'tünel', 'geçit', 'yol', 'cadde', 'sokak', 'bulvar', 'meydan',
  'park', 'bahçe', 'çimen', 'çimenlik', 'çalılık', 'ağaçlık', 'koruluk', 'mesire',
  'spor', 'futbol', 'basketbol', 'voleybol', 'hentbol', 'tenis', 'badminton', 'masa tenisi',
  'yüzme', 'dalış', 'su topu', 'sutopu', 'kürek', 'yelken', 'sörf', 'kano', 'rafting',
  'atletizm', 'koşu', 'maraton', 'sprint', 'bayrak', 'engelli', 'uzun atlama', 'yüksek atlama',
  'güreş', 'judo', 'karate', 'taekwondo', 'boks', 'kick boks', 'muay thai', 'aikido',
  'jimnastik', 'aerobik', 'pilates', 'yoga', 'fitness', 'vücut geliştirme', 'halter', 'ağırlık',
  'bisiklet', 'motosiklet', 'araba yarışı', 'ralli', 'formula', 'pist', 'devre', 'tur',
  'golf', 'bowling', 'bilardo', 'dart', 'okçuluk', 'atıcılık', 'eskrim', 'binicilik',
  'kayak', 'snowboard', 'paten', 'hokey', 'curling', 'kızak', 'bob', 'skeleton',
  'dağcılık', 'tırmanış', 'kamp', 'doğa yürüyüşü', 'trekking', 'safari', 'macera', 'ekstrem',
  'balık tutma', 'avcılık', 'kuş gözlemciliği', 'doğa fotoğrafçılığı', 'botanik', 'zooloji',
  'bilim', 'fizik', 'kimya', 'biyoloji', 'matematik', 'geometri', 'cebir', 'trigonometri',
  'astronomi', 'astroloji', 'uzay', 'gezegen', 'yıldız', 'galaksi', 'nebula', 'kuasar',
  'atom', 'molekül', 'element', 'bileşik', 'karışım', 'çözelti', 'asit', 'baz', 'tuz',
  'hücre', 'doku', 'organ', 'sistem', 'organizma', 'canlı', 'bitki', 'hayvan', 'mantar',
  'bakteri', 'virüs', 'parazit', 'mikroorganizma', 'mikroskop', 'teleskop', 'laboratuvar',
  'deney', 'gözlem', 'hipotez', 'teori', 'kanun', 'ilke', 'kural', 'formül', 'denklem',
  'teknoloji', 'inovasyon', 'buluş', 'keşif', 'patent', 'prototip', 'model', 'tasarım',
  'yazılım', 'donanım', 'program', 'uygulama', 'sistem', 'ağ', 'sunucu', 'veri tabanı',
  'internet', 'web', 'site', 'blog', 'forum', 'sosyal medya', 'e-posta', 'mesaj', 'sohbet',
  'oyun', 'video oyunu', 'konsol', 'joystick', 'gamepad', 'klavye', 'mouse', 'kulaklık',
  'ekonomi', 'finans', 'banka', 'kredi', 'borç', 'faiz', 'kâr', 'zarar', 'gelir', 'gider',
  'para', 'lira', 'dolar', 'euro', 'sterlin', 'yen', 'yuan', 'frank', 'ruble', 'peso',
  'borsa', 'hisse', 'tahvil', 'bono', 'fon', 'yatırım', 'portföy', 'risk', 'getiri',
  'ticaret', 'alışveriş', 'satış', 'pazarlama', 'reklam', 'tanıtım', 'kampanya', 'indirim',
  'şirket', 'firma', 'kuruluş', 'işletme', 'girişim', 'startup', 'holding', 'kooperatif',
  'yönetim', 'idare', 'organizasyon', 'planlama', 'strateji', 'taktik', 'hedef', 'amaç',
  'proje', 'görev', 'sorumluluk', 'yetki', 'karar', 'onay', 'izin', 'ruhsat', 'lisans',
  'sözleşme', 'anlaşma', 'protokol', 'mutabakat', 'uzlaşma', 'ittifak', 'ortaklık', 'işbirliği',
  'politika', 'hükümet', 'parlamento', 'meclis', 'senato', 'bakanlık', 'valilik', 'kaymakamlık',
  'seçim', 'oy', 'sandık', 'aday', 'parti', 'koalisyon', 'muhalefet', 'iktidar', 'demokrasi',
  'cumhuriyet', 'monarşi', 'oligarşi', 'aristokrasi', 'teokrasi', 'diktatörlük', 'totaliter',
  'anayasa', 'kanun', 'yasa', 'tüzük', 'yönetmelik', 'genelge', 'tebliğ', 'sirküler',
  'mahkeme', 'duruşma', 'dava', 'dava', 'sanık', 'mağdur', 'tanık', 'jüri', 'karar',
  'ceza', 'hapis', 'para cezası', 'tazminat', 'af', 'erteleme', 'şartlı tahliye', 'infaz',
  'suç', 'kabahat', 'kusur', 'hata', 'yanılgı', 'ihmal', 'kasıt', 'taksir', 'teşebbüs',
  'ahlak', 'erdem', 'fazilet', 'değer', 'ilke', 'prensip', 'kural', 'norm', 'gelenek',
  'örf', 'adet', 'töre', 'görenek', 'seremoni', 'protokol', 'nezaket', 'edep',
  'saygı', 'hürmet', 'ikram', 'alçak gönüllülük', 'kibir', 'gurur',
  'cesaret', 'yiğitlik', 'kahramanlık', 'fedakarlık', 'özgecilik', 'bencillik', 'cimrilik',
  'cömertlik', 'eli açıklık', 'kerem', 'ikram', 'bağış', 'yardım', 'destek', 'katkı',
  'dostluk', 'arkadaşlık', 'yoldaşlık', 'kardeşlik', 'birlik', 'beraberlik', 'dayanışma',
  'aile', 'akraba', 'hısım', 'soy', 'sülale', 'nesil', 'kuşak', 'evlat', 'torun', 'soy',
  'evlilik', 'nikah', 'düğün', 'nişan', 'söz', 'kına', 'gelin', 'damat', 'sağdıç',
  'doğum', 'bebek', 'çocukluk', 'gençlik', 'yetişkinlik', 'orta yaş', 'yaşlılık', 'ömür',
  'sağlık', 'hastalık', 'rahatsızlık', 'ağrı', 'acı', 'sızı', 'kramp', 'şişlik', 'kızarıklık',
  'ateş', 'öksürük', 'hapşırma', 'burun akıntısı', 'boğaz ağrısı', 'baş ağrısı', 'mide bulantısı',
  'grip', 'nezle', 'soğuk algınlığı', 'bronşit', 'zatürre', 'astım', 'alerji', 'egzama',
  'diyabet', 'tansiyon', 'kolesterol', 'kalp', 'damar', 'arter', 'ven', 'kan', 'plazma',
  'ilaç', 'hap', 'şurup', 'merhem', 'krem', 'sprey', 'damla', 'enjeksiyon', 'serum',
  'vitamin', 'mineral', 'protein', 'karbonhidrat', 'yağ', 'lif', 'kalori', 'besin', 'gıda',
  'diyet', 'rejim', 'perhiz', 'oruç', 'açlık', 'tokluk', 'iştah', 'mide', 'karın',
  'egzersiz', 'antrenman', 'çalışma', 'idman', 'kondisyon', 'form', 'kas', 'güç', 'dayanıklılık',
  'esneklik', 'denge', 'koordinasyon', 'refleks', 'hız', 'çeviklik', 'patlayıcılık', 'güç',
  'zihin', 'akıl', 'us', 'düşünce', 'fikir', 'görüş', 'kanı', 'inanç', 'itikat', 'mezhep',
  'hafıza', 'bellek', 'hatıra', 'anı', 'hatırlama', 'unutma', 'amnezi', 'nostalji',
  'hayal', 'düş', 'rüya', 'kabus', 'vizyon', 'imge', 'imaj', 'görüntü', 'sahne', 'manzara',
  'duygu', 'his', 'hissetme', 'duyumsama', 'algı', 'idrak', 'şuur', 'bilinç', 'farkındalık',
  'sevinç', 'neşe', 'şen', 'keyif', 'zevk', 'haz', 'lezzet', 'tat', 'aroma', 'koku',
  'keder', 'hüzün', 'melankoli', 'depresyon', 'bunalım', 'stres', 'kaygı', 'endişe', 'korku',
  'öfke', 'hiddet', 'gazap', 'kızgınlık', 'sinir', 'asabiyet', 'gerginlik', 'tansiyon',
  'şaşkınlık', 'hayret', 'dehşet', 'korku', 'ürperti', 'titreme', 'sarsılma', 'şok',
  'merak', 'ilgi', 'alaka', 'dikkat', 'konsantrasyon', 'odaklanma', 'yoğunlaşma', 'derin',
  'sabır', 'tahammül', 'dayanma', 'katlanma', 'bekleme', 'umut', 'ümit', 'beklenti', 'arzu',
  'istek', 'dilek', 'temenni', 'rica', 'niyaz', 'yalvarma', 'yakarma', 'dua', 'niyaz',
  'şükür', 'teşekkür', 'minnet', 'takdir', 'beğeni', 'övgü', 'methiye', 'senai', 'kaside',
  'eleştiri', 'tenkit', 'yergi', 'hiciv', 'taşlama', 'alay', 'istihza', 'kinaye', 'ironi',
  'mizah', 'komedi', 'espri', 'şaka', 'latife', 'nükte', 'fıkra', 'hikaye', 'masal',
  'efsane', 'destan', 'mit', 'mitoloji', 'söylence', 'rivayet', 'anlatı', 'öykü', 'roman',
  'şiir', 'nazım', 'manzume', 'kaside', 'gazel', 'rubai', 'koşuk', 'türkü', 'destan',
  'nesir', 'düz yazı', 'makale', 'deneme', 'eleştiri', 'inceleme', 'araştırma', 'tez',
  'gramer', 'sözdizimi', 'biçimbilim', 'anlambilim', 'sesbilim', 'yazım', 'imla', 'noktalama',
  'kelime', 'sözcük', 'terim', 'kavram', 'anlam', 'mana', 'meal', 'yorum', 'tefsir',
  'çeviri', 'tercüme', 'aktarma', 'uyarlama', 'adaptasyon', 'versiyon', 'baskı', 'yayın'
];
